# local transaction
db_type = "mysql"
row_count = 100
initial_balance = 1000
verbose = true
enable_cts = false

[check_balance]
enabled = true
threads = 10

[read_snapshot]
enabled = true
threads = 10

[read_too_old_snapshot]
enabled = true
threads = 1

[read_long]
enabled = true
threads = 10
interval = "5s"
total = "20m"

[check_secondary_index]
enabled = true
threads = 10

[transfer_simple]
enabled = true
threads = 10
